use anyhow::{Context, Result};
use colored::Colorize;
use schemagit_core::{Column, Table};
use schemagit_snapshot::SnapshotManager;

use super::{output, utils};

const UNIQUE_PREFIX: &str = "UNIQUE ";
const EMPTY: &str = "";

/// Execute the export command.
pub fn execute(
    snapshot_id: &str,
    directory: &str,
    format: &str,
    output_file: Option<&str>,
    yes: bool,
    no_create_dir: bool,
) -> Result<()> {
    let manager = SnapshotManager::new(directory);
    let snapshot = utils::resolve_snapshot(&manager, snapshot_id, directory)?;

    let rendered = match format.to_lowercase().as_str() {
        "sql" => {
            export_sql_string(&snapshot.schema.tables, &snapshot.database_type)
        }
        "json" => export_json(&snapshot)?,
        "yaml" => export_yaml(&snapshot),
        _ => {
            return Err(anyhow::anyhow!(
                "{}",
                format!("Unknown format: {}. Use sql, json, or yaml", format)
                    .red()
            ));
        }
    };

    output::write_or_stdout(
        &rendered,
        output_file,
        yes,
        no_create_dir,
        "Export",
    )?;

    Ok(())
}

/// Export schema as SQL CREATE statements (returned as a string).
fn export_sql_string(tables: &[Table], db_type: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("-- Schema export for {}\n", db_type));
    out.push_str("-- Generated by schemagit\n\n");

    for (i, table) in tables.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&export_table_sql_string(table, db_type));
        out.push('\n');
    }

    out
}

/// Export a single table as SQL (returned as a string).
fn export_table_sql_string(table: &Table, db_type: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "CREATE TABLE {} (\n",
        quote_identifier(db_type, &table.name)
    ));

    // Export columns
    let column_defs: Vec<String> = table
        .columns
        .iter()
        .map(|c| column_definition(c, db_type))
        .collect();
    out.push_str("  ");
    out.push_str(&column_defs.join(",\n  "));
    out.push_str("\n);\n");

    // Export indexes
    for index in &table.indexes {
        let unique = if index.unique { UNIQUE_PREFIX } else { EMPTY };
        let columns = index
            .columns
            .iter()
            .map(|c| quote_identifier(db_type, c))
            .collect::<Vec<_>>()
            .join(", ");

        out.push_str(&format!(
            "CREATE {}INDEX {} ON {} ({});\n",
            unique,
            quote_identifier(db_type, &index.name),
            quote_identifier(db_type, &table.name),
            columns
        ));
    }

    // Export foreign keys
    for fk in &table.foreign_keys {
        out.push_str(&format!(
            "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({});\n",
            quote_identifier(db_type, &table.name),
            quote_identifier(db_type, &fk.name),
            quote_identifier(db_type, &fk.column),
            quote_identifier(db_type, &fk.ref_table),
            quote_identifier(db_type, &fk.ref_column)
        ));
    }

    out
}

/// Generate column definition.
fn column_definition(column: &Column, db_type: &str) -> String {
    let mut parts = vec![
        quote_identifier(db_type, &column.name),
        column.data_type.clone(),
    ];

    if !column.nullable {
        parts.push("NOT NULL".to_string());
    }

    if let Some(ref default) = column.default {
        parts.push(format!("DEFAULT {}", default));
    }

    parts.join(" ")
}

fn quote_identifier(db_type: &str, name: &str) -> String {
    match db_type.to_lowercase().as_str() {
        "mssql" | "sqlserver" => format!("[{}]", name.replace(']', "]]")),
        _ => format!("\"{}\"", name.replace('\"', "\"\"")),
    }
}

/// Export snapshot as JSON.
fn export_json(snapshot: &schemagit_snapshot::Snapshot) -> Result<String> {
    let json = serde_json::to_string_pretty(snapshot)
        .context("Failed to serialize snapshot to JSON")?;
    Ok(json)
}

/// Export snapshot as YAML.
fn export_yaml(snapshot: &schemagit_snapshot::Snapshot) -> String {
    // Simple YAML-like output (without external dependency)
    let mut yaml = String::new();
    yaml.push_str(&format!("database_type: {}\n", snapshot.database_type));
    yaml.push_str(&format!(
        "timestamp: {}\n",
        snapshot.timestamp.format("%Y-%m-%d %H:%M:%S")
    ));
    yaml.push_str("schema:\n");
    yaml.push_str("  tables:\n");

    for table in &snapshot.schema.tables {
        yaml.push_str(&format!("    - name: {}\n", table.name));
        yaml.push_str("      columns:\n");
        for column in &table.columns {
            yaml.push_str(&format!("        - name: {}\n", column.name));
            yaml.push_str(&format!(
                "          data_type: {}\n",
                column.data_type
            ));
            yaml.push_str(&format!(
                "          nullable: {}\n",
                column.nullable
            ));
            if let Some(ref default) = column.default {
                yaml.push_str(&format!("          default: {}\n", default));
            }
        }

        if !table.indexes.is_empty() {
            yaml.push_str("      indexes:\n");
            for index in &table.indexes {
                yaml.push_str(&format!("        - name: {}\n", index.name));
                yaml.push_str(&format!("          unique: {}\n", index.unique));
                yaml.push_str("          columns:\n");
                for col in &index.columns {
                    yaml.push_str(&format!("            - {}\n", col));
                }
            }
        }

        if !table.foreign_keys.is_empty() {
            yaml.push_str("      foreign_keys:\n");
            for fk in &table.foreign_keys {
                yaml.push_str(&format!("        - name: {}\n", fk.name));
                yaml.push_str(&format!("          column: {}\n", fk.column));
                yaml.push_str(&format!(
                    "          ref_table: {}\n",
                    fk.ref_table
                ));
                yaml.push_str(&format!(
                    "          ref_column: {}\n",
                    fk.ref_column
                ));
            }
        }
    }

    yaml
}

#[cfg(test)]
mod tests {
    use super::*;
    use schemagit_core::Table;

    #[test]
    fn quote_identifier_mssql() {
        assert_eq!(quote_identifier("mssql", "users"), "[users]");
        assert_eq!(quote_identifier("mssql", "a]b"), "[a]]b]");
    }

    #[test]
    fn export_table_sql_string_mssql_uses_brackets() {
        let table = Table {
            name: "users".to_string(),
            columns: vec![Column {
                name: "id".to_string(),
                data_type: "int".to_string(),
                nullable: false,
                default: None,
            }],
            indexes: vec![],
            foreign_keys: vec![],
        };

        let sql = export_table_sql_string(&table, "mssql");
        assert!(sql.contains("CREATE TABLE [users]"));
        assert!(sql.contains("[id] int NOT NULL"));
    }
}
