use anyhow::{Context, Result};
use colored::Colorize;
use schemagit_core::{Column, Table};
use schemagit_snapshot::SnapshotManager;

/// Execute the export command.
pub fn execute(snapshot_id: &str, directory: &str, format: &str) -> Result<()> {
    let manager = SnapshotManager::new(directory);

    // Load snapshot
    let snapshot = if snapshot_id.ends_with(".snapshot.json") {
        manager.load(snapshot_id)?
    } else if snapshot_id == "latest" {
        manager
            .latest()
            .context("Failed to load latest snapshot")?
            .ok_or_else(|| {
                anyhow::anyhow!("No snapshots found in {}", directory)
            })?
    } else {
        // Convert ID to filename
        let filename = if snapshot_id.len() == 14 {
            format!(
                "{}_{}_{}_{}.snapshot.json",
                &snapshot_id[0..4],
                &snapshot_id[4..6],
                &snapshot_id[6..8],
                &snapshot_id[8..14]
            )
        } else {
            format!("{}.snapshot.json", snapshot_id)
        };
        manager.load(&filename)?
    };

    // Export based on format
    match format.to_lowercase().as_str() {
        "sql" => export_sql(&snapshot.schema.tables, &snapshot.database_type),
        "json" => export_json(&snapshot)?,
        "yaml" => export_yaml(&snapshot)?,
        _ => {
            println!(
                "{}",
                format!("Unknown format: {}. Use sql, json, or yaml", format)
                    .red()
            );
        }
    }

    Ok(())
}

/// Export schema as SQL CREATE statements.
fn export_sql(tables: &[Table], db_type: &str) {
    println!("-- Schema export for {}", db_type);
    println!("-- Generated by schemagit");
    println!();

    for table in tables {
        export_table_sql(table);
        println!();
    }
}

/// Export a single table as SQL.
fn export_table_sql(table: &Table) {
    println!("CREATE TABLE \"{}\" (", table.name);

    // Export columns
    let column_defs: Vec<String> =
        table.columns.iter().map(column_definition).collect();
    println!("  {}", column_defs.join(",\n  "));

    println!(");");

    // Export indexes
    for index in &table.indexes {
        let unique = if index.unique { "UNIQUE " } else { "" };
        let columns = index
            .columns
            .iter()
            .map(|c| format!("\"{}\"", c))
            .collect::<Vec<_>>()
            .join(", ");

        println!(
            "CREATE {}INDEX \"{}\" ON \"{}\" ({});",
            unique, index.name, table.name, columns
        );
    }

    // Export foreign keys
    for fk in &table.foreign_keys {
        println!(
            "ALTER TABLE \"{}\" ADD CONSTRAINT \"{}\" FOREIGN KEY (\"{}\") REFERENCES \"{}\" (\"{}\");",
            table.name, fk.name, fk.column, fk.ref_table, fk.ref_column
        );
    }
}

/// Generate column definition.
fn column_definition(column: &Column) -> String {
    let mut parts =
        vec![format!("\"{}\"", column.name), column.data_type.clone()];

    if !column.nullable {
        parts.push("NOT NULL".to_string());
    }

    if let Some(ref default) = column.default {
        parts.push(format!("DEFAULT {}", default));
    }

    parts.join(" ")
}

/// Export snapshot as JSON.
fn export_json(snapshot: &schemagit_snapshot::Snapshot) -> Result<()> {
    let json = serde_json::to_string_pretty(snapshot)
        .context("Failed to serialize snapshot to JSON")?;
    println!("{}", json);
    Ok(())
}

/// Export snapshot as YAML.
fn export_yaml(snapshot: &schemagit_snapshot::Snapshot) -> Result<()> {
    // Simple YAML-like output (without external dependency)
    println!("database_type: {}", snapshot.database_type);
    println!(
        "timestamp: {}",
        snapshot.timestamp.format("%Y-%m-%d %H:%M:%S")
    );
    println!("schema:");
    println!("  tables:");

    for table in &snapshot.schema.tables {
        println!("    - name: {}", table.name);
        println!("      columns:");
        for column in &table.columns {
            println!("        - name: {}", column.name);
            println!("          data_type: {}", column.data_type);
            println!("          nullable: {}", column.nullable);
            if let Some(ref default) = column.default {
                println!("          default: {}", default);
            }
        }

        if !table.indexes.is_empty() {
            println!("      indexes:");
            for index in &table.indexes {
                println!("        - name: {}", index.name);
                println!("          unique: {}", index.unique);
                println!("          columns:");
                for col in &index.columns {
                    println!("            - {}", col);
                }
            }
        }

        if !table.foreign_keys.is_empty() {
            println!("      foreign_keys:");
            for fk in &table.foreign_keys {
                println!("        - name: {}", fk.name);
                println!("          column: {}", fk.column);
                println!("          ref_table: {}", fk.ref_table);
                println!("          ref_column: {}", fk.ref_column);
            }
        }
    }

    Ok(())
}
